---
- name: Start re_dms
  systemd:
    name: re_dms
    state: restarted
    enabled: yes
    daemon_reload: yes
- name: Start transactions re_dms
  systemd:
    name: transactions_re_dms
    state: restarted
    enabled: yes
    daemon_reload: yes
